import { spawnSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

interface PnpmLicenseEntry {
  name: string;
  versions: string[];
  paths: string[];
  license: string;
  homepage?: string;
}

type PnpmLicenseReport = Record<string, PnpmLicenseEntry[]>;

const allowed = new Set([
  'MIT',
  'Apache-2.0',
  'BSD-2',
  'BSD-2-Clause',
  'BSD-3',
  'BSD-3-Clause',
  'ISC',
  'Zlib',
  '0BSD',
  'MPL-2.0',
  'Unlicense',
  'CC0',
]);
const generatedPath = path.join(process.cwd(), 'docs', 'THIRD-PARTY-LICENSES.md');

function licenceOptions(expression: string): string[] {
  return expression
    .replace(/[()]/g, '')
    .split(/\s+OR\s+|\s*\/\s*/i)
    .map((value) => value.trim())
    .filter(Boolean);
}

function isAllowed(expression: string): boolean {
  if (!expression || /^SEE LICENSE IN/i.test(expression)) return false;
  return licenceOptions(expression).some((option) => allowed.has(option));
}

async function loadReport(): Promise<PnpmLicenseReport> {
  if (process.env.CT_LICENSE_REPORT) {
    return JSON.parse(await readFile(process.env.CT_LICENSE_REPORT, 'utf8')) as PnpmLicenseReport;
  }
  const command = process.platform === 'win32' ? 'pnpm.CMD' : 'pnpm';
  const result = spawnSync(command, ['licenses', 'list', '--json'], {
    cwd: process.cwd(),
    encoding: 'utf8',
    shell: process.platform === 'win32',
  });
  if (result.status !== 0) throw new Error(result.stderr || 'pnpm licenses list failed.');
  return JSON.parse(result.stdout) as PnpmLicenseReport;
}

function flatten(report: PnpmLicenseReport): PnpmLicenseEntry[] {
  return Object.values(report)
    .flat()
    .sort(
      (left, right) =>
        left.name.localeCompare(right.name) || left.license.localeCompare(right.license),
    );
}

async function render(entries: PnpmLicenseEntry[]): Promise<string> {
  const assetRows = JSON.parse(
    await readFile(path.join(process.cwd(), 'docs', 'static-assets.json'), 'utf8'),
  ) as Array<{
    path: string;
    license: string;
    sourceUrl: string;
    licenseUrl: string;
    sha256: string;
    dateChecked: string;
  }>;
  const dependencyRows = entries.flatMap((entry) =>
    entry.versions.map(
      (version) =>
        `| \`${entry.name}\` | \`${version}\` | ${entry.license} | ${entry.homepage ? `[source](${entry.homepage})` : '—'} |`,
    ),
  );
  const assets = assetRows.map(
    (asset) =>
      `| \`${asset.path}\` | ${asset.license} | [source](${asset.sourceUrl}) · [licence](${asset.licenseUrl}) | \`${asset.sha256}\` | ${asset.dateChecked} |`,
  );
  return `${[
    '# Third-party licences',
    '',
    '> Generated by `pnpm verify:licenses:write`. Do not edit manually.',
    '',
    '## Package dependencies',
    '',
    '| Package | Version | Licence | Project |',
    '| --- | --- | --- | --- |',
    ...dependencyRows,
    '',
    '## Static assets',
    '',
    '| Asset | Licence | Provenance | SHA-256 | Checked |',
    '| --- | --- | --- | --- | --- |',
    ...(assets.length > 0
      ? assets
      : ['| _No third-party static assets registered._ | — | — | — | — |']),
    '',
  ].join('\n')}\n`;
}

const entries = flatten(await loadReport());
const failures = entries.filter((entry) => !isAllowed(entry.license));
if (failures.length > 0) {
  throw new Error(
    `Dependency licence gate failed:\n${failures.map((entry) => `- ${entry.name}@${entry.versions.join(', ')}: ${entry.license || 'missing/unknown'}`).join('\n')}`,
  );
}

if (process.env.CT_LICENSE_REPORT) {
  console.log(`Synthetic licence report passed for ${entries.length} dependencies.`);
  process.exit(0);
}

const generated = await render(entries);
if (process.argv.includes('--write')) {
  await writeFile(generatedPath, generated);
  console.log(
    `Wrote ${path.relative(process.cwd(), generatedPath)} for ${entries.length} dependencies.`,
  );
} else {
  let committed = '';
  try {
    committed = await readFile(generatedPath, 'utf8');
  } catch {
    throw new Error('docs/THIRD-PARTY-LICENSES.md is missing; run pnpm verify:licenses:write.');
  }
  if (committed !== generated) {
    throw new Error('docs/THIRD-PARTY-LICENSES.md is stale; run pnpm verify:licenses:write.');
  }
  console.log(`Verified ${entries.length} dependency licence records.`);
}
