/**
 * P5-17 — the `docs/PROVIDERS.md` generator (README §22.7 step 4, §15.2 item 3).
 *
 * §15.2 says "`docs/PROVIDERS.md` therefore always reflects reality, and the connect page can warn
 * *before* the user pastes a key". That is the document's entire purpose: it is the thing a reader
 * consults to find out whether a provider will work from their browser, so it has to be generated
 * from the same data the adapters declare rather than written by hand and left to rot.
 *
 * Two rules make it a generator rather than a document somebody edits:
 *
 * 1. **No clock in the output.** The freshness date comes from the run report's `generatedAt`, which
 *    the runner sets once. A generator that stamped `new Date()` would rewrite the file on every run
 *    and make every night a diff, which would train reviewers to ignore it. A run whose content is
 *    unchanged rewrites the file byte for byte.
 * 2. **No hand-maintained prose inside the generated region.** Every table cell is derived from a
 *    descriptor or a check result. Anything a person needs to say goes in the hand-written header
 *    above the marker, which the generator never touches.
 *
 * The CORS column is the one worth reading twice. It prints `browserDirect` **and** how that value
 * was arrived at — verified in a browser, or unverified and why. §15.2's argument is that a guess is
 * worse than an admission, and a table that printed a bare `yes` with no provenance would be
 * indistinguishable from one where nobody checked.
 */

import type { ContractRunReport, ProviderReport } from './types.js';

/** Where the generated table starts. Everything above this line is hand-written and preserved. */
export const PROVIDERS_DOC_BEGIN = '<!-- BEGIN GENERATED: p5-17 -->';
/** Where it ends. Everything below is hand-written and preserved. */
export const PROVIDERS_DOC_END = '<!-- END GENERATED: p5-17 -->';

/** What a CORS column cell must convey: the value, and whether anyone proved it. */
function corsCell(provider: ProviderReport): string {
  const check = provider.checks.find((entry) => entry.kind === 'browserDirect');
  if (!check?.browserOutcome)
    return `\`${provider.browserDirectInSource ?? 'unknown'}\` (not probed)`;

  const { browserDirect, unavailable } = check.browserOutcome;
  if (unavailable) return `\`${browserDirect}\` — not verified (${unavailable})`;
  const status = check.httpStatus === undefined ? '' : `, HTTP ${check.httpStatus}`;
  return `\`${browserDirect}\` — verified in a browser${status}`;
}

/**
 * Render the generated region.
 *
 * Takes the report and the `browserDirect` value each adapter source currently declares. The second
 * argument matters: when a provider was not probed, the document must still show what the source
 * says rather than blank, so that a reader is never left guessing which claim is in the repository.
 */
export function renderProvidersDoc(report: ContractRunReport): string {
  const lines: string[] = [];
  lines.push(PROVIDERS_DOC_BEGIN);
  lines.push('');
  lines.push(
    `<!-- Generated by \`pnpm test:contract:live\` on ${report.generatedAt}. Do not edit. -->`,
  );
  lines.push('');
  lines.push('| Provider | Capabilities | Works in a browser | Verified | Models | Last check |');
  lines.push('| --- | --- | --- | --- | --- | --- |');
  for (const provider of report.providers) {
    const test = provider.checks.find((check) => check.kind === 'test');
    lines.push(
      `| [${provider.name}](${provider.homepage}) | ${provider.capabilities.join(', ')} | ` +
        `${corsCell(provider)} | ${test ? test.status : 'not run'} | ${provider.modelIds.join(', ')} | ` +
        `${report.generatedAt} |`,
    );
  }
  lines.push('');
  lines.push('### Notes');
  lines.push('');
  lines.push(
    '- **Verified in a browser** means a real Playwright browser context issued the request and read ' +
      'the response. A Node-side request cannot establish this: it has no origin, so the provider ' +
      'never sees a preflight.',
  );
  lines.push(
    '- **not verified** means the job could not reach a verdict — most often because the provider ' +
      'answers from a network the runner cannot reach. It is not a "no".',
  );
  lines.push(
    `- Spend for this run: **$${report.totalSpentUsd}** against a hard cap of ` +
      `**$${report.spendCapUsd}**. Per-provider spend is in the job report.`,
  );
  lines.push('');
  lines.push(
    `Providers with no credential configured and therefore not contacted: ${
      report.unconfiguredProviders.length > 0 ? report.unconfiguredProviders.join(', ') : 'none'
    }.`,
  );
  lines.push('');
  lines.push(PROVIDERS_DOC_END);
  return lines.join('\n');
}

/**
 * Replace the generated region of an existing document, leaving hand-written prose intact.
 *
 * When the document has no markers yet — which is the case for the file this P5-17 introduces — the
 * hand-written preamble is supplied and the generated region is appended. Doing it this way rather
 * than by whole-file rewrite means a later edit to the surrounding explanation is never lost.
 */
export function upsertProvidersDoc(
  existing: string | undefined,
  generated: string,
  preamble: string,
): string {
  const begin = existing?.indexOf(PROVIDERS_DOC_BEGIN) ?? -1;
  const end = existing?.indexOf(PROVIDERS_DOC_END) ?? -1;
  if (begin !== -1 && end !== -1 && end > begin) {
    const before = (existing ?? '').slice(0, begin).trimEnd();
    const after = (existing ?? '').slice(end + PROVIDERS_DOC_END.length).trim();
    return `${join(before, generated, after)}\n`;
  }
  return `${join(preamble.trimEnd(), generated)}\n`;
}

/** Join the document's parts with a blank line between them, dropping empty ones. */
function join(...parts: readonly string[]): string {
  return parts.filter((part) => part.length > 0).join('\n\n');
}

/** The hand-written part of `docs/PROVIDERS.md`. Never generated, never overwritten. */
export const PROVIDERS_DOC_PREAMBLE = `# AI providers

Every provider below is bring-your-own-key: the key is pasted into your browser, stored on your
machine, and sent by your browser to the provider. It never reaches our servers. See
[Privacy](/connect-ai/privacy) for exactly what that does and does not cover.

The table is generated by the nightly live contract job
([README §22.7](https://github.com/) §22.7) and regenerated whenever a provider's browser behaviour
or model list changes.

## What "works in a browser" means

A provider that this app can call directly from a page sends your key straight from your browser to
the provider. Some providers allow that. Some do not — their servers refuse requests that did not
come from a registered origin, and the browser blocks the response before JavaScript ever sees it.

When a provider will not, the call has to go through a relay: a small server *you* deploy, on *your*
account, which adds the CORS headers and forwards the request. We host no relay and offer no shared
one, because a relay that we hosted would be a server we could read keys from.

The column below records what a real browser was observed doing, not what a provider's documentation
claims. A value of \`unknown\` means nobody has checked — treat it as genuinely unknown rather than as
a stale yes.
`;
